title: Teal Software Solutions
author: Tim Morgan
email: TMorgan99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site.
  Currently accepting projects


# social links
twitter_username: tmorgan99
github_username:  tmorgan99

show_excerpts: true # set to false to remove excerpts on the homepage

# theme: jekyll-theme-architect
theme: minima
